//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.23 at 11:37:48 AM WAT 
//


package xml.soap.station;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="idEstacao" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="qtd" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idEstacao",
    "qtd"
})
@XmlRootElement(name = "DocaCreat")
public class DocaCreat {

    protected long idEstacao;
    protected int qtd;

    /**
     * Gets the value of the idEstacao property.
     * 
     */
    public long getIdEstacao() {
        return idEstacao;
    }

    /**
     * Sets the value of the idEstacao property.
     * 
     */
    public void setIdEstacao(long value) {
        this.idEstacao = value;
    }

    /**
     * Gets the value of the qtd property.
     * 
     */
    public int getQtd() {
        return qtd;
    }

    /**
     * Sets the value of the qtd property.
     * 
     */
    public void setQtd(int value) {
        this.qtd = value;
    }

}
