//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.24 at 02:30:55 PM WAT 
//


package xml.soap.station;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstacaoCreatResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstacaoCreatResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="erro" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mensagem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dadosEstacao" type="{http://station.soap.xml}Estacao"/&gt;
 *         &lt;element name="docas" type="{http://station.soap.xml}AllDocasResponse"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstacaoCreatResponse", propOrder = {
    "erro",
    "mensagem",
    "dadosEstacao",
    "docas"
})
public class EstacaoCreatResponse {

    protected boolean erro;
    @XmlElement(required = true)
    protected String mensagem;
    @XmlElement(required = true)
    protected Estacao dadosEstacao;
    @XmlElement(required = true)
    protected AllDocasResponse docas;

    /**
     * Gets the value of the erro property.
     * 
     */
    public boolean isErro() {
        return erro;
    }

    /**
     * Sets the value of the erro property.
     * 
     */
    public void setErro(boolean value) {
        this.erro = value;
    }

    /**
     * Gets the value of the mensagem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensagem() {
        return mensagem;
    }

    /**
     * Sets the value of the mensagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensagem(String value) {
        this.mensagem = value;
    }

    /**
     * Gets the value of the dadosEstacao property.
     * 
     * @return
     *     possible object is
     *     {@link Estacao }
     *     
     */
    public Estacao getDadosEstacao() {
        return dadosEstacao;
    }

    /**
     * Sets the value of the dadosEstacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Estacao }
     *     
     */
    public void setDadosEstacao(Estacao value) {
        this.dadosEstacao = value;
    }

    /**
     * Gets the value of the docas property.
     * 
     * @return
     *     possible object is
     *     {@link AllDocasResponse }
     *     
     */
    public AllDocasResponse getDocas() {
        return docas;
    }

    /**
     * Sets the value of the docas property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllDocasResponse }
     *     
     */
    public void setDocas(AllDocasResponse value) {
        this.docas = value;
    }

}
