//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.24 at 02:30:55 PM WAT 
//


package xml.soap.station;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.station package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.station
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStationDetailsRequest }
     * 
     */
    public GetStationDetailsRequest createGetStationDetailsRequest() {
        return new GetStationDetailsRequest();
    }

    /**
     * Create an instance of {@link EstacaoCreat }
     * 
     */
    public EstacaoCreat createEstacaoCreat() {
        return new EstacaoCreat();
    }

    /**
     * Create an instance of {@link AllEstacoesRequest }
     * 
     */
    public AllEstacoesRequest createAllEstacoesRequest() {
        return new AllEstacoesRequest();
    }

    /**
     * Create an instance of {@link AllEstacoesResponse }
     * 
     */
    public AllEstacoesResponse createAllEstacoesResponse() {
        return new AllEstacoesResponse();
    }

    /**
     * Create an instance of {@link EstacaoModelXSD }
     * 
     */
    public EstacaoModelXSD createEstacaoModelXSD() {
        return new EstacaoModelXSD();
    }

    /**
     * Create an instance of {@link GetStationResponse }
     * 
     */
    public GetStationResponse createGetStationResponse() {
        return new GetStationResponse();
    }

    /**
     * Create an instance of {@link DockType }
     * 
     */
    public DockType createDockType() {
        return new DockType();
    }

    /**
     * Create an instance of {@link GetStationRequest }
     * 
     */
    public GetStationRequest createGetStationRequest() {
        return new GetStationRequest();
    }

    /**
     * Create an instance of {@link AlterStateDockBikeRequest }
     * 
     */
    public AlterStateDockBikeRequest createAlterStateDockBikeRequest() {
        return new AlterStateDockBikeRequest();
    }

    /**
     * Create an instance of {@link AlterStateDockBikeResponse }
     * 
     */
    public AlterStateDockBikeResponse createAlterStateDockBikeResponse() {
        return new AlterStateDockBikeResponse();
    }

    /**
     * Create an instance of {@link AddDockRequest }
     * 
     */
    public AddDockRequest createAddDockRequest() {
        return new AddDockRequest();
    }

    /**
     * Create an instance of {@link AddDockResponse }
     * 
     */
    public AddDockResponse createAddDockResponse() {
        return new AddDockResponse();
    }

    /**
     * Create an instance of {@link DeleteDockRequest }
     * 
     */
    public DeleteDockRequest createDeleteDockRequest() {
        return new DeleteDockRequest();
    }

    /**
     * Create an instance of {@link DeleteDockResponse }
     * 
     */
    public DeleteDockResponse createDeleteDockResponse() {
        return new DeleteDockResponse();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link GetStationDetailsRequest.Body }
     * 
     */
    public GetStationDetailsRequest.Body createGetStationDetailsRequestBody() {
        return new GetStationDetailsRequest.Body();
    }

    /**
     * Create an instance of {@link GetStationDetailsResponse }
     * 
     */
    public GetStationDetailsResponse createGetStationDetailsResponse() {
        return new GetStationDetailsResponse();
    }

    /**
     * Create an instance of {@link AddDocaRequest }
     * 
     */
    public AddDocaRequest createAddDocaRequest() {
        return new AddDocaRequest();
    }

    /**
     * Create an instance of {@link AddDocaResponse }
     * 
     */
    public AddDocaResponse createAddDocaResponse() {
        return new AddDocaResponse();
    }

    /**
     * Create an instance of {@link DocaXSD }
     * 
     */
    public DocaXSD createDocaXSD() {
        return new DocaXSD();
    }

    /**
     * Create an instance of {@link GetAllDocaRequest }
     * 
     */
    public GetAllDocaRequest createGetAllDocaRequest() {
        return new GetAllDocaRequest();
    }

    /**
     * Create an instance of {@link GetAllDocaResponse }
     * 
     */
    public GetAllDocaResponse createGetAllDocaResponse() {
        return new GetAllDocaResponse();
    }

    /**
     * Create an instance of {@link StationRequest }
     * 
     */
    public StationRequest createStationRequest() {
        return new StationRequest();
    }

    /**
     * Create an instance of {@link Estacao }
     * 
     */
    public Estacao createEstacao() {
        return new Estacao();
    }

    /**
     * Create an instance of {@link EstacaoCreatResponse }
     * 
     */
    public EstacaoCreatResponse createEstacaoCreatResponse() {
        return new EstacaoCreatResponse();
    }

    /**
     * Create an instance of {@link Doca }
     * 
     */
    public Doca createDoca() {
        return new Doca();
    }

    /**
     * Create an instance of {@link AllDocasResponse }
     * 
     */
    public AllDocasResponse createAllDocasResponse() {
        return new AllDocasResponse();
    }

    /**
     * Create an instance of {@link AddInfoStationRequest }
     * 
     */
    public AddInfoStationRequest createAddInfoStationRequest() {
        return new AddInfoStationRequest();
    }

    /**
     * Create an instance of {@link AddInfoStationResponse }
     * 
     */
    public AddInfoStationResponse createAddInfoStationResponse() {
        return new AddInfoStationResponse();
    }

}
