//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.24 at 02:30:55 PM WAT 
//


package xml.soap.user;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xml.soap.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xml.soap.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserForIdRequest }
     * 
     */
    public UserForIdRequest createUserForIdRequest() {
        return new UserForIdRequest();
    }

    /**
     * Create an instance of {@link HeaderRequest }
     * 
     */
    public HeaderRequest createHeaderRequest() {
        return new HeaderRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link UserListResponse }
     * 
     */
    public UserListResponse createUserListResponse() {
        return new UserListResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link UserForIdRequest.Body }
     * 
     */
    public UserForIdRequest.Body createUserForIdRequestBody() {
        return new UserForIdRequest.Body();
    }

    /**
     * Create an instance of {@link CiclistaLoginRequest }
     * 
     */
    public CiclistaLoginRequest createCiclistaLoginRequest() {
        return new CiclistaLoginRequest();
    }

    /**
     * Create an instance of {@link GestorLoginRequest }
     * 
     */
    public GestorLoginRequest createGestorLoginRequest() {
        return new GestorLoginRequest();
    }

    /**
     * Create an instance of {@link UserResponse }
     * 
     */
    public UserResponse createUserResponse() {
        return new UserResponse();
    }

    /**
     * Create an instance of {@link CiclistaCreat }
     * 
     */
    public CiclistaCreat createCiclistaCreat() {
        return new CiclistaCreat();
    }

    /**
     * Create an instance of {@link UserCreat }
     * 
     */
    public UserCreat createUserCreat() {
        return new UserCreat();
    }

    /**
     * Create an instance of {@link UserUpdateRequest }
     * 
     */
    public UserUpdateRequest createUserUpdateRequest() {
        return new UserUpdateRequest();
    }

    /**
     * Create an instance of {@link UserUpdatePasswordRequest }
     * 
     */
    public UserUpdatePasswordRequest createUserUpdatePasswordRequest() {
        return new UserUpdatePasswordRequest();
    }

    /**
     * Create an instance of {@link UserClientResponse }
     * 
     */
    public UserClientResponse createUserClientResponse() {
        return new UserClientResponse();
    }

    /**
     * Create an instance of {@link UsersListResponse }
     * 
     */
    public UsersListResponse createUsersListResponse() {
        return new UsersListResponse();
    }

    /**
     * Create an instance of {@link UserToListType }
     * 
     */
    public UserToListType createUserToListType() {
        return new UserToListType();
    }

    /**
     * Create an instance of {@link EmailUserRequest }
     * 
     */
    public EmailUserRequest createEmailUserRequest() {
        return new EmailUserRequest();
    }

    /**
     * Create an instance of {@link GestorCreat }
     * 
     */
    public GestorCreat createGestorCreat() {
        return new GestorCreat();
    }

    /**
     * Create an instance of {@link UserGestorResponse }
     * 
     */
    public UserGestorResponse createUserGestorResponse() {
        return new UserGestorResponse();
    }

}
