//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.24 at 02:30:55 PM WAT 
//


package xml.soap.user;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="erro" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="mensagem" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dadosUser" type="{http://user.soap.xml}User"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "erro",
    "mensagem",
    "dadosUser"
})
@XmlRootElement(name = "UserResponse")
public class UserResponse {

    protected boolean erro;
    @XmlElement(required = true)
    protected String mensagem;
    @XmlElement(required = true)
    protected User dadosUser;

    /**
     * Gets the value of the erro property.
     * 
     */
    public boolean isErro() {
        return erro;
    }

    /**
     * Sets the value of the erro property.
     * 
     */
    public void setErro(boolean value) {
        this.erro = value;
    }

    /**
     * Gets the value of the mensagem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMensagem() {
        return mensagem;
    }

    /**
     * Sets the value of the mensagem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMensagem(String value) {
        this.mensagem = value;
    }

    /**
     * Gets the value of the dadosUser property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getDadosUser() {
        return dadosUser;
    }

    /**
     * Sets the value of the dadosUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setDadosUser(User value) {
        this.dadosUser = value;
    }

}
